### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by Cynjaman1019** [OyotOnyenwe/clubsite#1]
"competitive" misspelled as "competitve"
https://github.com/OyotOnyenwe/clubsite/blob/8bd84bc066d10b4adc509ac587377dfde288a860/esports.html#L44

Tournaments not up-to-date
https://github.com/OyotOnyenwe/clubsite/blob/8bd84bc066d10b4adc509ac587377dfde288a860/tournaments.html

**Comment by OyotOnyenwe** [comment]
fixed typo & updated tournaments as of 6/2/2023
